sudo: false
language: node_js
services:
  - mongodb
  - mysql
node_js:
  - '4.0'
install: npm install
script: npm test
before_script:
  - sleep 15
  - mysql -e 'create database angular_full_sequelize;'
after_script: npm run report-coverage
